url: "https://korisalapitvany.github.io"

# Build settings
markdown: kramdown
plugins:
- jekyll-coffeescript
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap

sass:
  style: compressed

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- Makefile
- README.md
- third_party/
- vendor/
- src/
